"""add_schema2_tables_video_conversations_conversation_messages_videos_catalog

Revision ID: 471c628dd18d
Revises: 2b0d3ffc5704
Create Date: 2025-11-17 01:52:32.724703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '471c628dd18d'
down_revision: Union[str, Sequence[str], None] = '2b0d3ffc5704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos_catalog',
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=False),
    sa.Column('channel_title', sa.String(length=300), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=False),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('embedding_version', sa.String(length=50), nullable=True),
    sa.Column('last_embedded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('video_id')
    )
    op.create_table('video_conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('video_title', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_user_message', sa.Text(), nullable=True),
    sa.Column('last_assistant_message', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('synopsis_preview', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video')
    )
    op.create_index(op.f('ix_video_conversations_is_pinned'), 'video_conversations', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_video_conversations_last_message_at'), 'video_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_video_conversations_user_id'), 'video_conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_video_conversations_video_id'), 'video_conversations', ['video_id'], unique=False)
    
    # MANUALLY ADDED: Composite indexes for video_conversations
    # These are CRITICAL for tab query performance (per chatSchema.md lines 46-49)
    op.create_index(
        'ix_video_conversations_user_pinned_last_message',
        'video_conversations',
        ['user_id', sa.text('is_pinned DESC'), sa.text('last_message_at DESC')]
    )
    op.create_index(
        'ix_video_conversations_user_last_message',
        'video_conversations',
        ['user_id', sa.text('last_message_at DESC')]
    )
    
    # MANUALLY ADDED: Partial index for retention job efficiency (chatSchema.md line 49)
    # This speeds up the "find unpinned conversations to delete" query
    op.execute("""
        CREATE INDEX ix_video_conversations_user_unpinned_last_message 
        ON video_conversations (user_id, last_message_at DESC) 
        WHERE is_pinned = false
    """)
    
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.String(length=11), nullable=False),
    sa.Column('message_index', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_length', sa.Integer(), nullable=False),
    sa.Column('tokens_estimate', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant', 'system')", name='check_role_valid'),
    sa.ForeignKeyConstraint(['conversation_id'], ['video_conversations.conversation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'message_index', name='uq_conversation_message_index')
    )
    op.create_index(op.f('ix_conversation_messages_user_id'), 'conversation_messages', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_video_id'), 'conversation_messages', ['video_id'], unique=False)
    
    # MANUALLY ADDED: Missing single-column index for conversation_id
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    
    # MANUALLY ADDED: Composite indexes for conversation_messages
    # These enable efficient conversation thread loading and user/video queries (chatSchema.md lines 76-80)
    op.create_index(
        'ix_conversation_messages_conversation_index',
        'conversation_messages',
        ['conversation_id', 'message_index']
    )
    op.create_index(
        'ix_conversation_messages_conversation_created',
        'conversation_messages',
        ['conversation_id', 'created_at']
    )
    op.create_index(
        'ix_conversation_messages_user_video_created',
        'conversation_messages',
        ['user_id', 'video_id', 'created_at']
    )
    
    # REMOVED: Legacy table index drops - not part of Phase 0
    # These were auto-detected by Alembic but should not be dropped until Phase 5
    # op.drop_index('idx_messages_created', table_name='messages')
    # op.drop_index('idx_messages_session_order', table_name='messages')
    # op.drop_index('idx_messages_video', table_name='messages', postgresql_where='(video_id IS NOT NULL)')
    # op.drop_constraint('uq_session_message_index', 'messages', type_='unique')
    # op.drop_index('idx_sessions_cleanup', table_name='user_sessions', postgresql_where='(is_active = true)')
    # op.drop_index('idx_sessions_user_active', table_name='user_sessions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop in REVERSE order: child tables first, parent tables last
    # This prevents foreign key constraint violations
    
    # Drop videos_catalog (no dependencies)
    op.drop_table('videos_catalog')
    
    # Drop conversation_messages (child of video_conversations)
    # MANUALLY ADDED: Drop manually created composite indexes first
    op.drop_index('ix_conversation_messages_user_video_created', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_created', table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_index', table_name='conversation_messages')
    # Drop auto-generated indexes
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_video_id'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_user_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    
    # Drop video_conversations (parent table, drop last)
    # MANUALLY ADDED: Drop manually created indexes first
    op.execute("DROP INDEX IF EXISTS ix_video_conversations_user_unpinned_last_message")
    op.drop_index('ix_video_conversations_user_last_message', table_name='video_conversations')
    op.drop_index('ix_video_conversations_user_pinned_last_message', table_name='video_conversations')
    # Drop auto-generated indexes
    op.drop_index(op.f('ix_video_conversations_video_id'), table_name='video_conversations')
    op.drop_index(op.f('ix_video_conversations_user_id'), table_name='video_conversations')
    op.drop_index(op.f('ix_video_conversations_last_message_at'), table_name='video_conversations')
    op.drop_index(op.f('ix_video_conversations_is_pinned'), table_name='video_conversations')
    op.drop_table('video_conversations')
    
    # REMOVED: Legacy table index recreations - not part of Phase 0
    # These were auto-generated but should not be touched until Phase 5
    # op.create_index('idx_sessions_user_active', 'user_sessions', ...)
    # op.create_index('idx_sessions_cleanup', 'user_sessions', ...)
    # op.create_unique_constraint('uq_session_message_index', 'messages', ...)
    # op.create_index('idx_messages_video', 'messages', ...)
    # op.create_index('idx_messages_session_order', 'messages', ...)
    # op.create_index('idx_messages_created', 'messages', ...)
    # ### end Alembic commands ###
